apiVersion: v1
data:
  config.json: |
    {
      "config_ini": {{ .Values.configJson.config_ini | quote }}{{","}}
      "config_method": {{ .Values.configJson.config_method | quote }}{{","}}
      "namespace": {{ .Release.Namespace | quote }}{{","}}
      "kms_url": "https://{{ .Values.global.kmsVaultHostConfig.name }}:{{ .Values.global.kmsVaultHostConfig.port }}"
    }
kind: ConfigMap
metadata:
  name: {{ include "eric-swgwda.fullname" . }}-configjson-map
